sudo: required
language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "katarinaa94-github"
    token: $SONAR_TOKEN

script:
  - ./mvnw clean install -DskipTests=false -B
  - ./mvnw sonar:sonar   -Dsonar.projectKey=katarinaa94_testing   -Dsonar.organization=katarinaa94-github   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=$SONAR_TOKEN

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: testing-isa